services:
  db_postgres_sorteador_live:
    image: postgres
    container_name: db_postgres_sorteador_live
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg_sorteador_live:/var/lib/postgresql/data

  node_app_sorteador_live:
    container_name: node_app_sorteador_live
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_sorteador_live
    env_file:
      - ./back-end/.env

  react_sorteador_app_live:
    container_name: react_sorteador_app_live
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx_sorteador_app_live:
    container_name: nginx_sorteador_app_live
    build: ./nginx
    image: nginx_sorteador_app_live_image
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_postgres_sorteador_live
      - node_app_sorteador_live
      - react_sorteador_app_live

volumes:
  pg_sorteador_live:
  build_react:
