services:
  db_postgres_sorteador_live:
    image: postgres
    container_name: db_postgres_sorteador_live
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env.test

  node_app_sorteador_live:
    container_name: node_app_sorteador_live
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_sorteador_live
    env_file:
      - ./back-end/.env.test
