services:
  db_postgres_sorteador_live:
    image: postgres
    container_name: db_postgres_sorteador_live
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg_sorteador_live:/var/lib/postgresql/data

  node_app_sorteador_live:
    container_name: sorteador_live
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_sorteador_live
    env_file:
      - .env

volumes:
  pg_sorteador_live:
